# Generated by Django 4.0.4 on 2022-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('msg', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('address', models.CharField(max_length=200, verbose_name='Company')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('city', models.CharField(max_length=200, verbose_name='Phone')),
                ('province', models.CharField(max_length=200, verbose_name='Phone')),
                ('zipcode', models.CharField(max_length=20, verbose_name='Phone')),
                ('cost', models.CharField(max_length=2000, verbose_name='Cost')),
                ('count', models.CharField(max_length=200, verbose_name='Count')),
                ('ordersize', models.CharField(max_length=200, verbose_name='Order Size')),
            ],
        ),
    ]
